# Generated by Django 3.2.4 on 2021-07-03 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('activity', models.CharField(max_length=100, verbose_name='Activity')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('coupon_name', models.CharField(max_length=64, verbose_name='Coupon Name')),
                ('coupon_type', models.IntegerField(choices=[(1, '满减优惠券'), (2, '通用优惠券')], verbose_name='Coupon Type')),
                ('amount', models.CharField(max_length=32, verbose_name='Equivalent Amount')),
                ('coupon_number', models.PositiveIntegerField(verbose_name='Quantity')),
                ('min_amount', models.CharField(default=0, help_text='Fill in when the coupon is full or reduced', max_length=32, verbose_name='Min Amount')),
                ('receive_time', models.DateTimeField(verbose_name='Start Time')),
                ('effective_time', models.DateTimeField(verbose_name='Effective Time')),
                ('invalid_time', models.DateTimeField(verbose_name='Expiration Time')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
            },
        ),
        migrations.CreateModel(
            name='WechatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('user_uuid', models.CharField(max_length=64, unique=True, verbose_name='uuid')),
                ('username', models.CharField(max_length=32, null=True, verbose_name='User Name')),
                ('user_js_code', models.CharField(max_length=64, verbose_name='User Js Code')),
                ('login_time', models.DateTimeField(auto_now=True, verbose_name='Login Time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('token', models.UUIDField(verbose_name='token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coupon.wechatuser', verbose_name='Relate User')),
            ],
            options={
                'verbose_name': 'token',
                'verbose_name_plural': 'token',
            },
        ),
        migrations.CreateModel(
            name='CouponUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
                ('status', models.IntegerField(choices=[(1, '未使用'), (2, '已使用'), (3, '已过期')], verbose_name='用户优惠券状态')),
                ('obtain_time', models.DateTimeField(verbose_name='领取时间')),
                ('coupon_use_time', models.DateTimeField(null=True, verbose_name='使用时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon', verbose_name='优惠券')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.wechatuser', verbose_name='绑定用户')),
            ],
            options={
                'verbose_name': '优惠券使用记录',
                'verbose_name_plural': '优惠券使用记录',
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
