# Generated by Django 3.2.4 on 2021-07-02 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('activity', models.CharField(max_length=100, verbose_name='活动')),
            ],
            options={
                'verbose_name': '04-活动',
                'verbose_name_plural': '04-活动',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('client', models.CharField(max_length=100, verbose_name='机构')),
            ],
            options={
                'verbose_name': '02-机构',
                'verbose_name_plural': '02-机构',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('coupon_name', models.CharField(max_length=64, verbose_name='优惠券标题')),
                ('coupon_type', models.IntegerField(choices=[(1, '满减优惠券'), (2, '通用优惠券')], verbose_name='优惠券类型')),
                ('amount', models.CharField(max_length=32, verbose_name='等值金额')),
                ('coupon_number', models.PositiveIntegerField(verbose_name='数量')),
                ('min_amount', models.CharField(default=0, help_text='满减劵时填写', max_length=32, verbose_name='最低消费金额')),
                ('receive_time', models.DateTimeField(verbose_name='优惠券开始发放时间')),
                ('effective_time', models.DateTimeField(verbose_name='优惠券生效时间')),
                ('invalid_time', models.DateTimeField(verbose_name='优惠券失效时间')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.activity', verbose_name='活动')),
            ],
            options={
                'verbose_name': '06-优惠券',
                'verbose_name_plural': '06-优惠券',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('user_uuid', models.CharField(max_length=64, unique=True, verbose_name='uuid')),
                ('username', models.CharField(max_length=32, null=True, verbose_name='用户名')),
                ('user_js_code', models.CharField(max_length=64, verbose_name='用户js_code')),
                ('login_time', models.DateTimeField(auto_now=True, verbose_name='登录时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '01-用户表',
                'verbose_name_plural': '01-用户表',
            },
        ),
        migrations.CreateModel(
            name='Verifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('verifier', models.CharField(max_length=100, verbose_name='核销员')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.client', verbose_name='机构')),
            ],
            options={
                'verbose_name': '03-核销员',
                'verbose_name_plural': '03-核销员',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('token', models.UUIDField(verbose_name='token')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coupon.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '05-token',
                'verbose_name_plural': '05-token',
            },
        ),
        migrations.CreateModel(
            name='CouponUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.IntegerField(choices=[(1, '未使用'), (2, '已使用'), (3, '已过期')], verbose_name='用户优惠券状态')),
                ('obtain_time', models.DateTimeField(verbose_name='领取时间')),
                ('coupon_use_time', models.DateTimeField(null=True, verbose_name='使用时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon', verbose_name='优惠券')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.user', verbose_name='绑定用户')),
            ],
            options={
                'verbose_name': '07-优惠券使用记录',
                'verbose_name_plural': '07-优惠券使用记录',
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
