# Generated by Django 3.2.4 on 2021-07-02 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifier',
            name='client',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': '优惠券', 'verbose_name_plural': '优惠券'},
        ),
        migrations.AlterModelOptions(
            name='couponuse',
            options={'verbose_name': '优惠券使用记录', 'verbose_name_plural': '优惠券使用记录'},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name': 'token', 'verbose_name_plural': 'token'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '微信用户', 'verbose_name_plural': '微信用户'},
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Verifier',
        ),
    ]
