# Generated by Django 3.2.4 on 2021-07-03 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(max_length=100, verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.activity', verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.CharField(max_length=32, verbose_name='等值金额'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_name',
            field=models.CharField(max_length=64, verbose_name='优惠券标题'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_number',
            field=models.PositiveIntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.IntegerField(choices=[(1, '满减优惠券'), (2, '通用优惠券')], verbose_name='优惠券类型'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='effective_time',
            field=models.DateTimeField(verbose_name='优惠券生效时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='invalid_time',
            field=models.DateTimeField(verbose_name='优惠券失效时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_amount',
            field=models.CharField(default=0, help_text='满减劵时填写', max_length=32, verbose_name='最低消费金额'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='receive_time',
            field=models.DateTimeField(verbose_name='优惠券开始发放时间'),
        ),
        migrations.AlterField(
            model_name='couponuse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='couponuse',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='token',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='token',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coupon.wechatuser', verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='login_time',
            field=models.DateTimeField(auto_now=True, verbose_name='登录时间'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='user_js_code',
            field=models.CharField(max_length=64, verbose_name='用户js_code'),
        ),
        migrations.AlterField(
            model_name='wechatuser',
            name='username',
            field=models.CharField(max_length=32, null=True, verbose_name='用户名'),
        ),
    ]
