# Generated by Django 3.2.4 on 2021-07-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_coupon_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='brief',
            field=models.TextField(blank=True, null=True, verbose_name='活动介绍'),
        ),
    ]
