# Generated by Django 3.2.4 on 2021-07-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210703_2051'),
        ('coupon', '0004_activity_brief'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponuse',
            name='verifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client.verifier', verbose_name='核销员'),
        ),
        migrations.AlterField(
            model_name='couponuse',
            name='coupon_use_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='使用时间'),
        ),
    ]
