# Generated by Django 3.2.4 on 2021-07-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210703_2051'),
        ('coupon', '0005_auto_20210703_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='client',
            field=models.ManyToManyField(blank=True, null=True, to='client.Client', verbose_name='机构'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='coupon.WechatUser', verbose_name='用户'),
        ),
    ]
