# Generated by Django 3.2.4 on 2021-07-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_auto_20210704_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='coupon.WechatUser', verbose_name='用户'),
        ),
    ]
